os: osx
language: swift
osx_image: xcode9.3

branches:
    only:
    - master

script:
    - xcodebuild clean build test -project EmojiOne.xcodeproj -scheme EmojiOne -destination 'platform=iOS Simulator,name=iPhone X' CODE_SIGNING_REQUIRED=NO | xcpretty

notifications:
email:
    on_success: never
    on_failure: change
